CC = gcc
CFLAGS = -g -Wall -Wpedantic -std=c17
LDFLAGS =
LDLIBS =

.PHONY: default
default: fork-and fork-or fork-buf

fork-and:
fork-or:
fork-buf:

.PHONY: clean
clean:
	rm -rf a.out *.o fork-and fork-or fork-buf
