CC = gcc
CFLAGS = -g -Wall -Wpedantic -std=c17
LDFLAGS =
LDLIBS =

.PHONY: default
default: fgtest dcat decho

fgtest: freegrind.o
freegrind.o:
fgtest.o:

dcat:
decho:

.PHONY: clean
clean:
	rm -rf *.o a.out fgtest dcat decho
