CC = gcc
CFLAGS = -g -Wall -Wpedantic -std=c17 -Wno-unused-variable -Wno-nonnull

.PHONY: default
default: myarchive myarchive-sol myexpand myexpand-sol

myarchive:
myarchive-sol:
myexpand:
myexpand-sol:

.PHONY: clean
clean:
	rm -rf *.o a.out myarchive myarchive-sol myexpand myexpand-sol
