CC = gcc
CFLAGS = -g -Wall -Wpedantic -std=c17
LDFLAGS =
LDLIBS =

.PHONY: default
default: tcp-echo-client tcp-echo-server

tcp-echo-client:
tcp-echo-server:

.PHONY: clean
clean:
	rm -rf a.out *.o tcp-echo-client tcp-echo-server
