CC = gcc
CFLAGS = -g -Wall -Wpedantic -std=c17

# By default, build all of targets
.PHONY: default
default: ncat cp cp-broken
ncat:
cp:
cp-broken:

.PHONY: clean
clean:
	rm -rf *.o a.out ncat cp cp-broken
