CC = gcc
CFLAGS = -g -Wall -Wpedantic -std=c17
LDFLAGS =
LDLIBS =

.PHONY: default
default: multi-http-server

http-server:

.PHONY: clean
clean:
	rm -rf a.out *.o multi-http-server

.PHONY: all
all: clean multi-http-server
